
title: My Resume
url: 'https://xbreizh.github.io/cv/#'
baseurl: '/xavier_lamourec/' #change it according to your repository name



# Profile information
yourname: Xavier Lamourec  ## put your name
title: 'JAVA Developer'  ## your title
location: Dundalk, Ireland


## Social Profiles
#facebook: http://www.facebook.com  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
#linkedin: http://www.linkedin.com  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
github: http://www.github.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
